--   AsmBASIC - a BASIC interpreter written in assembly language
--   Copyright (C) 2022  Ekkehard Morgenstern
--
--   This program is free software: you can redistribute it and/or modify
--   it under the terms of the GNU General Public License as published by
--   the Free Software Foundation, either version 3 of the License, or
--   (at your option) any later version.
--
--   This program is distributed in the hope that it will be useful,
--   but WITHOUT ANY WARRANTY; without even the implied warranty of
--   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
--   GNU General Public License for more details.
--
--   You should have received a copy of the GNU General Public License
--   along with this program.  If not, see <https://www.gnu.org/licenses/>.
--
--   NOTE: Programs created with AsmBASIC do not fall under this license.
--
--   CONTACT INFO:
--       E-Mail: ekkehard@ekkehardmorgenstern.de
--       Mail: Ekkehard Morgenstern, Mozartstr. 1, D-76744 Woerth am Rhein,
--             Germany, Europe

TOKEN p-exponent := /P[+-][0-9]+/ .

TOKEN hex-exponent := /G[+-][0-9A-F]+/ | p-exponent .
TOKEN dec-exponent := /E[+-][0-9]+/ | p-exponent .
TOKEN oct-exponent := /E[+-][0-7]+/ | p-exponent .
TOKEN bin-exponent := /E[+-][0-1]+/ | p-exponent .

TOKEN hex-number := '&H' /([0-9A-F]+)?(\.[0-9A-F]+)?/ [hex-exponent] .
TOKEN dec-number := ['&D'] /([0-9]+)?(\.[0-9]+)?/ [dec-exponent] .
TOKEN oct-number := '&O' /([0-7]+)?(\.[0-7]+)?/ [oct-exponent] .
TOKEN bin-number := '&B' /([0-1]+)?(\.[0-1]+)?/ [bin-exponent] .

TOKEN number := hex-number | dec-number | oct-number | bin-number .
