#!/usr/bin/perl -w

my $branch = `git branch --no-color | egrep '^\*' | cut -d ' ' -f 2- | egrep -o 'v[0-9.]+'`;
chomp $branch;

my $lasttag;
if ( $branch ne '' ) {
    $lasttag = $branch;
} else {
    $lasttag = `git tag --list | tail -n 1`;
    chomp $lasttag;
}

open FILE,">verstr.inc";
print FILE "; generated by tagtoverstr.pl, DO NOT MODIFY!!\n\n";
print FILE "                    db  '$lasttag'\n";
close FILE;
